version: '3'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  gerapy-redis-example:
    container_name: 'gerapy-redis-example'
    restart: always
    build: .
    image: 'germey/gerapy-redis-example'
    command: 'scrapy crawl movie'
    environment:
      REDIS_URL: 'redis://@redis:6379'
    depends_on:
      - redis